apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: kavya
  region: us-east-2

managedNodeGroups:
  - name: kavya
    instanceTypes: ["c4.large","c5.large"]
    desiredCapacity: 3
    spot: true