apiVersion: eksctll.io/v1alpha5
kind: ClusterConfig

metadata:
  name: expenses
  region: us-east-1

managedNodeGroups:
  - name: expenses
    instanceTypes: ["m5.large", "c3.large","c4.large","c5.large"]
    desiredCapacity: 3
    spot: true