apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: expense
  region: us-east-2

managedNodeGroups:
  - name: expense
    instanceTypes: ["m5.large", "t3.medium"]
    desiredCapacity: 3
    spot: true